### ISSUE TITLE
0.5.0 release checklist

### ISSUE THREAD

**Issue by Guard13007** [cc-paw/cc-paw#27]
- [x] Update version number in src/lib.lua
- [x] Update version number in src/manual.txt
- [x] Update version number in src/pkg.lua
- [x] Update changes.log
- [x] Update revision number in src/installer.lua (IF NEEDED)
- [x] Update CC-PAW.zip (IF NEEDED)
- [x] Update installer script on Pastebin (IF NEEDED)
- [x] Update example-package-info.lua (IF NEEDED)
- [x] Duplicate `src` into `releases/cc-paw/[version]`
- [x] Update version number in releases/packages.list
- [x] Merge `dev` branch into `gh-pages`
- [x] Tag and draft release on GitHub. Remember to upload CC-PAW.zip!
