### ISSUE TITLE
Initial installer todo

### ISSUE THREAD

**Issue by Guard13007** [cc-paw/cc-paw#3]
- [x] Basically is a copy of the install part of CC-PAW, but hardcoded to only use this directory to do the install.
- [x] Since cc-paw is itself just another package, after this initial install, everything should be awesome.
- [x] Note: Make sure the installer pulls the latest version before installing, so it can always be used to install the latest version. NOTE: IT SHOULD ONLY USE COMPATIBLE VERSIONS AS DEFINED BY SEMVER!!!

**Comment by Guard13007** [comment]
Actually, the installer should just install a minimal version of cc-paw (bare minimum files for it to function) and then run:

```
cc-paw update
cc-paw upgrade
```

**Comment by Guard13007** [comment]
NOTE CURRENT INSTALLER IS ACTUALLY BROKEN! It assumes sources.list exists!

Also double check that FS API creates non-existent directories for me.

**Comment by Guard13007** [comment]
I think everything is great. I'm just gonna try it and break what it fixes.
