### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by Guard13007** [cc-paw/cc-paw#5]
- [x] FEATURE: remove option in files, including support for directory removal
- [x] BUG: installed list needs to be generated, NOT specified (right now it would overwrite any past instance of itself)
- [x] Feature? add a warning for removing cc-paw itself (this will make you unable to install packages, including cc-paw itself, without running the installer again (place an emergency cc-paw installer in /bin/cc-paw-install?)
- [x] test upgrading cc-paw
- [x] Improvement: files need to be optional in package specifications
- [x] FEATURE: dependencies need to be allowed

----

- [x] FIRST, fix what is a bug, only make things ready for upgrades
- [x] THEN, add new features into a 0.2.0 cc-paw release (this is when I can test upgrades!)

**Comment by Guard13007** [comment]
Testing now!

**Comment by Guard13007** [comment]
**NOTE**: This test is of the upgrade process, not of the new features.

**Comment by Guard13007** [comment]
Upgrading did not work as expected...will investigate...

**Comment by Guard13007** [comment]
Will make a new issue about upgrading, closing this.
