### ISSUE TITLE
todo list 2

### ISSUE THREAD

**Issue by Guard13007** [cc-paw/cc-paw#6]
- [ ] Make sources file able to have comments in it?
- [ ] Add option to upgrade a specific package only.
- [ ] Clean up messy code (file handles left open).
- [ ] Make purge and remove not require an internet connection? (yes, because security/it's stupid to have to connect)
- [ ] Make upgrading check for existence of config files and install them if they do not exist.
- [ ] Add autoremove (searches dependency list and removes any not needed)
- [ ] Add search (specify name and return partial matches for packages)
- [ ] Add list (lists all installed packages and their current versions)
- [ ] Document postInstallCode, postRemoveCode ??
- [ ] Add preInstallCode, preRemoveCode, prePurgeCode, postPurgeCode, preUpgradeCode, postUpgradeCode
      (Add ability for custom code to flag a cancel/skip install, so they can do what they want.)
      OR NOT
- [ ] Related ideas: tree (directory tree), more (output control), format (format disks/drives)

**Comment by Guard13007** [comment]
In 0.3.0, postInstallCode and postRemoveCode were removed, as they did not see use and are likely to never have a use. Additionally, adding more points for custom code seems pointless at this time, so I'm checking those as "done" even though they aren't.
